Feature/about page
nameless-mc/hack-viewer-web-client pull request #10
Opened 2022-12-10 10:55 UTC by Kouki2022

about と使い方ページ作成
ハリボテです。

2022-12-10 12:12 UTC, nameless-mc requested changes

2022-12-10 12:12 UTC, nameless-mc commented on hack-viewer/src/components/pages/AboutPage.jsx
> +                        </Typography>
見出しが共通なのでコンポーネント化してもいいかも

2022-12-10 12:12 UTC, nameless-mc commented on hack-viewer/src/components/pages/AboutPage.jsx
> +                        <Typography style={{ color: 'orange' }} Box sx={{fontSize:30,mt:7}}>
```suggestion
                        <Typography style={{ color: 'orange' }} Box sx={{fontWeight:'bold',fontSize:30,mt:7,mb:2}}>
```

2022-12-10 12:12 UTC, nameless-mc commented on hack-viewer/src/components/pages/AboutPage.jsx
> +                            3.開発チーム
ここに開発チームがあるのはおかしい気がする

2022-12-10 12:12 UTC, nameless-mc commented on hack-viewer/src/components/pages/HowtoPage.jsx
> +                        </Typography>
こちらもコンポーネント化しても良いかも

2022-12-10 12:12 UTC, nameless-mc commented on hack-viewer/src/components/pages/HowtoPage.jsx
> +                            <Box sx={{fontSize:17,ml:7,mt:2}}>
```suggestion
                            <Box sx={{fontWeight:'bold', fontSize:17,ml:7,mt:2}}>
```

もしくは他のテキストの `fontWeight` を調整

2022-12-10 12:12 UTC, nameless-mc commented on hack-viewer/src/components/pages/HowtoPage.jsx
> +                            For participant
日本語の方が自然な気がする

2022-12-10 12:12 UTC, nameless-mc commented on hack-viewer/src/components/pages/HowtoPage.jsx
> +                            For Host
For participant と For Host の統一感がなくて違和感...

2022-12-10 12:12 UTC, nameless-mc commented on hack-viewer/src/components/pages/HowtoPage.jsx
> +                            (1)イベントページで自チームの「進捗をPUSHするボタン」を押す<br/>
```suggestion
                            (1)イベントページで自チームの「進捗をPUSHする」ボタンを押す<br/>
```

2022-12-10 12:16 UTC, nameless-mc commented
追加しておくと良いこと
- `AboutPage` と `HowtoPage`  のルーティング設定を `MainRouter` に追加
- ページ遷移の導線を追加

2022-12-11 04:15 UTC, Kouki2022 commented on hack-viewer/src/components/pages/AboutPage.jsx
> +                        </Typography>
やり方が分からずこのまま・・・・

2022-12-11 04:16 UTC, Kouki2022 commented on hack-viewer/src/components/pages/AboutPage.jsx
> +                        <Typography style={{ color: 'orange' }} Box sx={{fontSize:30,mt:7}}>
修正

2022-12-11 04:16 UTC, Kouki2022 commented on hack-viewer/src/components/pages/AboutPage.jsx
> +                            3.開発チーム
修正

2022-12-11 04:17 UTC, Kouki2022 commented on hack-viewer/src/components/pages/HowtoPage.jsx
> +                        </Typography>
やり方分からず・・・

2022-12-11 04:23 UTC, Kouki2022 commented
結局ページ遷移が分からず。。。

2022-12-11 05:01 UTC, merged